### PR TITLE
Update API to Urho3D 1.6 (Apr 16, 2017).

### PR DESCRIPTION
**Pull request by xiliu98**
Update API to Urho3D 1.6 (Apr 16, 2017).
More options.

### CODE REVIEW

**Comment by pkulchenko** [comment]
@silverkorn, want to review the proposed changes, as I'm not familiar with the plugin details?

**Comment by pkulchenko** [comment]
@silverkorn, do you have time to check the changes?

**Comment by silverkorn** [comment]
Sure, I'll take a look during this week.

**Comment by silverkorn** [comment]
Sorry, I took a look on my side but I realized that this was a Pull request.
@xiliu98 , did you generate it with the suggested steps at the beginning of this file or you managed to add them manually?

**Comment by xiliu98** [comment]
Yes, I generate it with the suggested steps, then I removed some wrong text from the output text, and add some useful options for convenience to debug.

**Comment by silverkorn** [comment]
@pkulchenko, then I approve this PR! 😜 
@xiliu98, do you have an example of wrong text so I could try to re-adapt the original script?
You can also increment the minor version number at the end of this API script.
By the way, I'd like to thank you a lot for the update of this API! 😃

**Comment by xiliu98** [comment]
@silverkorn Sorry, I have delete the original file.
But it is very easy to find out, because the ZeroBrane IDE will hint the error message.

**Comment by silverkorn** [comment]
Ok, thanks. I'll check this out when I'll have a moment.
@pkulchenko, feel free to merge when you have a moment!

**Comment by pkulchenko** [comment]
@xiliu98, merged; thank you! You may need to force-push the changes into your master branch (or re-fork) as I ended up cherry-picking the changes.

@silverkorn, thank you for taking look!

**Pull request closed without merging**
