### PR TITLE
MCServer: Added whole-project analysis.

### PR DESCRIPTION
**Pull request by madmaxoft**
This concatenates all files in the project in the order MCServer loads them, then analyzes the string, and parses the results back into the original files.

### CODE REVIEW

**Comment by pkulchenko** [comment]
@Mattes, I'm going to merge this, but you do know that there is `Analyze All` plugin that does static analysis on all files in a project, right?

**Comment by madmaxoft** [comment]
Yes, I based my plugin on it; however, it doesn't do what I need - it examines each file separately, while my plugin concatenates all files together (as does the interpreter itself - MCServer). This makes difference since the latter allows implicit cross-file globals - define a global function in one file and use it in another, without loading or requiring the first file explicitly.

**Comment by pkulchenko** [comment]
Good point; I didn't realize that. It may be interesting to generalize that as it didn't occur to me previously: we can look at the project files and figure out where the globals are assigned and where they are used. Then order the files based on the number of dependencies and analyze the aggregated file (but keeping the references to map back to the original files). This assumes that the files are loaded by the project in the right order, but I think it's a good assumption to make to minimize the number of false positives.

Is that what you do for your case?

**Comment by madmaxoft** [comment]
MCServer loads the files in a well-defined order (alphabetically, case-sensitive, except for the Info.lua file which is always loaded last), so that's what the plugin is using.
If you wanted to add a generalization in the form of "analyze this set of files as a single unit", then okay, it might help, you can even use most of the plugin's analysis code as the base for that. But I don't really see a use-case, because this special handling is specific to the interpreter and unlikely to be used by other interpreters.

**Comment by pkulchenko** [comment]
True, although ZBS code itself is structured in a similar way, but the order of the files is quite specific and is hardcoded in `main.lua`.

Anyway, I just wanted to get a bit more information on this and it was one of the ideas that came to me ;).

**Pull request merged**
