### PR TITLE
Added a comment in/out package

### PR DESCRIPTION
**Pull request by NiLSPACE**
It allows users to comment the lines they have selected in or out.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Btw, I tried to bind `ctrl + q`, because I'm used to that from notepad++, but I wasn't able to do that because that's also a shortcut to shutting ZeroBrane off. Is there a way to disable that?

**Comment by NiLSPACE** [comment]
Seriously? When I finaly finish this, I find out that there already is something for it. `Ctrl + U`. Though I do notice that it doesn't handle indents really well.

**Comment by pkulchenko** [comment]
Yes, there is `Ctrl+U` that does comment/uncomment. We can fix it if it doesn't deal with indents, although it should.

Yes, you can update `Ctrl+Q` to do something else; for example, add `keymap[ID.EXIT] = nil` to the config file and then set `Ctrl+Q` to whatever you need.

**Comment by NiLSPACE** [comment]
`Ctrl+U` places the comments on the start of the line, not after any indents. But that could also be intentional.

Thanks for the `Ctrl+Q` solution :)

**Comment by pkulchenko** [comment]
Yes, that's intentional as it makes it easier to set/remove comments; otherwise it's difficult to figure out (algorithmically) where the comments that are set using `Ctrl-U` and where the other (normal) comments are.

Ok, closing this one. Don't hesitate to ask on the maillist or in IRC (#zerobrane on freenode) as ZBS already includes quite a bit and there is always some new functionality in the works to avoid duplication.

**Pull request closed without merging**
