### PR TITLE
Make the "TODO" patterns configurable

### PR DESCRIPTION
**Pull request by Tieske**
Allows to modify the patterns and have multiple

### CODE REVIEW

**Comment by pkulchenko** [comment]
Looks good, but the default pattern is not the same as shown in the docs:

```
+      self.patterns = { "TODO[:;]", "FIXME[:;]" }
+  patterns = { "TODO[%s:;]", "FIXME[%s:;]" },
```

Is it intentional?

**Comment by Tieske** [comment]
you mean the comment at the bottom? yes, intential, why would a user change them otherwise?

**Comment by pkulchenko** [comment]
I got that, but I was thinking that you may want `TODO[%s:;]` by default, so `TODO something` also works, but it's your choice ;).

**Comment by Tieske** [comment]
fine as it is imo.

**Comment by pkulchenko** [comment]
Merged; thanks for the patch!

**Pull request closed without merging**
