### PR TITLE
adds tasks.lua

### PR DESCRIPTION
**Pull request by paul-reilly**
Here's the plugin so far. It was very close to a Theseus's paradox with little from todoall.lua left so I gave it a new name. I've documented it at the top of the file, there's a right-click menu to change functionality as well as new settings for user.lua. It does single files like todo or project wide like todoall.

Please feel free to criticise anything at all about it or me. :)

### CODE REVIEW

**Comment by pkulchenko** [comment]
@paul-reilly, Thank you for putting it together! I pushed a bunch of changes to https://github.com/pkulchenko/ZeroBranePackage/tree/tasks, which includes all of your changes, plus several improvements. I made them as separate commits, so you can review them.

I'm still thinking about flattening the structure (to remove TODO/FIXME level) and making the navigation to work on a single click instead of a double click. I see this panel looking very similar to Outline, just with the TODO labels instead of functions there.

The changes I pushed also improve performance on projects with large number of files with TODO text (as it delays the processing till the IDE is loaded or the project is switched). Take a look and let me know what you think.

**Comment by paul-reilly** [comment]
Cool, thanks very much for taking the time to go over it so thoroughly and to spare me the embarrassment of what you replaced with...

    config.showOnlyFilesWithTasks = sOFWT == nil or sOFWT == true

... staying there (what was I thinking?!?). :)

One issue with the 28a8f66 is that I did try freezing just the TreeCtrl, but there was still flickering, which is why I froze the whole notebook. I've checked the new version and the flickering is still there with the change (this is Windows 10).

The checkboxes in the right click menu are much better, they aren't initialized with the config values at the moment though...

    rcMenu:Check(ID_FILESWITHTASKS, config.showOnlyFilesWithTasks)
    rcMenu:Check(ID_SINGLEFILEMODE, config.singleFileMode)

...but they are a lot more sensible.

Re flattening, I did think of that as an option, but not to get rid of entirely. I was actually thinking of adding live filtering via a right-click or key command to only show specific tokens. I don't know if I'm just getting carried away though and having a more unified look would be good too.

**Comment by pkulchenko** [comment]
> One issue with the 28a8f66 is that I did try freezing just the TreeCtrl, but there was still flickering, which is why I froze the whole notebook. I've checked the new version and the flickering is still there with the change (this is Windows 10).

Interesting; I don't see much flicker on Win 8, but the problem with freezing is that if there is any issue with the earlier code, then the `Thaw` call is not done and the entire notebook is left white. If this works better for you, then leave freezing for the notebook there, but you probably need to wrap the code between Freeze/Thaw into pcall to make sure that the errors are handled.

> The checkboxes in the right click menu are much better, they aren't initialized with the config values at the moment though...

Yes, I just put `true` values there, so having `config` values there is better.

> Re flattening, I did think of that as an option, but not to get rid of entirely. I was actually thinking of adding live filtering via a right-click or key command to only show specific tokens. I don't know if I'm just getting carried away though and having a more unified look would be good too.

I think it's fine if you want to make it configurable. My personal preference would be to make it similar to Outline/Markers; the Markers panel shows the lines with the markers, so the Tasks panel can do something similar.

I'll make the two updates you suggested above and will force push the changes.

Also, in terms of the names, it may make sense to use `ide:GetDocument(editor):GetTabText()` to get the file names, as it integrates well with the editor and other plugins (for example, uniquetabname).

**Comment by pkulchenko** [comment]
Pushed the updates.

**Comment by paul-reilly** [comment]
That's filtering tasks added. Btw the line counting bug we discovered will still be in todo.all, so it might be worth updating it too. You can see from the commits there that I committed into the wrong branch earlier.

Re the unique tab names, using GetTabText() would make having all tasks from all project files shown difficult, unless I am missing something? The only sensible solution I can think of would be to update the tree as and when we open files, but while this makes perfect sense for Outline and Markers I think a project wide view of tasks ideally shouldn't require opening files to check if there are any tasks first.

If there's some kind of background loading thing that could be put into a coroutine then that would be better, but comparing all project files vs all loaded files would take a while.

**Comment by pkulchenko** [comment]
Looks super with all the changes! There is little bit of commit cleanup to do, but I can do it before the merge.

> The only sensible solution I can think of would be to update the tree as and when we open files, but while this makes perfect sense for Outline and Markers I think a project wide view of tasks ideally shouldn't require opening files to check if there are any tasks first.

I agree.

> If there's some kind of background loading thing that could be put into a coroutine then that would be better, but comparing all project files vs all loaded files could take a while.

There is no background loading, but you can do something similar to what I've done with file indexing (as it also needs to open all files in the project and parse/index them). You may check `indexFromQueue()` function in `outline.lua` as it "waits" for the current editor to be idle and then starts the indexing process. After one file is done, it re-inserts itself into "idle" tasks until the queue is empty. It works fairly well and doesn't load the editor when the user is doing something in it. Let me know if you want to pursue this path as I'll need to add `GetLastUpdated()` (or something similar) method for the editor (instead of `editor.updated`). `TimeGet` will also need to be renamed and changed to a method.

You can then first show those files that are currently open and index the rest of them using this "delayed" method. Other than that, I don't have any suggestions. I think it works very well!

**Comment by pkulchenko** [comment]
@paul-reilly, there was a small glitch in scrolling as `ScrollTo` and `EnsureVisible` both shift the position of the tree control to make the maximum of the line visible, which also involves horizontal shift. The following code for ensureFileNodeVisible should avoid that:

```lua
tree.scrollTo = function(fileNode)
  if tree.ctrl:IsVisible(fileNode) then return end
  tree.ctrl:Freeze()
  tree.ctrl:ScrollTo(fileNode)
  tree.ctrl:SetScrollPos(wx.wxHORIZONTAL, 0, true)
  tree.ctrl:Thaw()
end   

--
tree.ensureFileNodeVisible = function(fileNode)
  -- ensure file node and last gradnchild/child is visible so that
  -- it's all in view
  local lastChild = tree.ctrl:GetLastChild(fileNode)
  if lastChild then
    if config.showNames then
      local lastGrandChild = tree.ctrl:GetLastChild(lastChild)
      if lastGrandChild then
        tree.scrollTo(lastGrandChild)
        return
      end
    end
  end
  tree.scrollTo(fileNode)
end
```

**Comment by paul-reilly** [comment]
Thanks! Yes, the scroll issue was annoying me and I missed SetScrollPos in the wxTreeCtrl hierarchy - I was actually going to ask about that.

I think I'll leave it at this at the moment, improving scanning would be good but maybe for later.

I just need to tidy up a couple of things. While I was doing conditional cancelling selection on changing focus if it's not the current file, I noticed that the userdata for the wxTreeItemId reference is different every time it's accessed...

    local fi = tree.ctrl:GetItemParent(fileItem)
        for i = 1, 10 do
          _DBG(fi == tree.ctrl:GetItemParent(fileItem))
    end

... so I couldn't compare them. I'm using the item data instead, but the userdata should ideally be the same if it's a reference to the same object.

Anyway, I'll do a final check over and push probably tonight.

**Comment by pkulchenko** [comment]
> ... so I couldn't compare them. I'm using the item data instead, but the userdata should ideally be the same if it's a reference to the same object.

Yes, it's a feature of the implementation in wxwidgets. You can use `GetValue()` method on the item (so it will be `fileItem:GetValue()` in your case), which provides a unique id that doesn't change until the item is deleted from the tree.

> Anyway, I'll do a final check over and push probably tonight.

Sounds good.

**Comment by paul-reilly** [comment]
That should be it finished now, yay!

It's probably a Win 10 thing, but I tackled the last remaining flicker issues with freezing the proj notebook, inc in the scrollTo function. Without freezing the notebook, at worse scroll bars appear (this was earlier on in development when doing major things to the tree) and disappear and at best there's a small flicker.

**Comment by pkulchenko** [comment]
Nice! Couple of things I noticed (hope the last batch ;)):

1. border needs to be removed to be consistent with other trees; it was in [one of my commits](https://github.com/pkulchenko/ZeroBranePackage/pull/59/commits/4cad2a988b7a452fa676ce768f9b971bf5c39296), but probably got lost with the changes.
2. I remembered why you can't freeze the Project notebook: it's because the tab can be dragged out, in which case it gets its own notebook assigned. I think you can use `:GetParent()` on the tree control to find its parent, but will need to check on macOS, as it may have one more layer there. Then you can freeze the parent.
3. Something has changed with the positioning logic as it scrolls to the wrong position to me (not all, but most of the time) and I remember it was working correctly yesterday. It's likely because you removed the `IsVisible` check. I think if you add `if tree.ctrl:IsVisible(fileNode) then return end` as the first line in `tree.scrollTo` it may be better. (checking...) Hm, no, still jumps to the wrong position. (checking more...) I got it. I think it should only jump if the filename for the item you clicked on is not visible, and event that is probably questionable (if there is a long list of items in the file, the item you clicked on will more out of the view). Maybe it's a result of miscalculation of the file node as I see occasional cases when the wrong file name gets bolded after a click. These two may be related. I need to play a bit more with it to see what's going on.
4. `noButtons` check needs a small fix, otherwise it tries to add boolean in `hasButtons` and fails:

```
    local hasButtons = self:GetConfig().noButtons and 0 or wx.wxTR_HAS_BUTTONS
    local linesAtRoot = self:GetConfig().noButtons and 0 or wx.wxTR_LINES_AT_ROOT
```

**Comment by paul-reilly** [comment]
Thanks again for the feedback and keen eye!

1. No probs, done.
2. Okay, I'll check that out - I don't have easy access to a Mac but if two levels up is Mac and one is Windux then I can do that.
3. Yes, I see that now. It works perfectly, then something makes it not work. I'll tidy up the highlighting stuff to see what's happening.
4. It does work, in the comments I mention that you set it to 0 and not true, but it's very lazy so I'll change it.

**Comment by pkulchenko** [comment]
> Okay, I'll check that out - I don't have easy access to a Mac but if two levels up is Mac and one is Windux then I can do that.

I'll double check there later today, but something like this should work (you can search for this fragment in main.lua):

```lua
        local nbc = "wxAuiNotebook"
        local notebook = win:GetClassInfo():GetClassName() == nbc and win:DynamicCast(nbc)
        or win:GetParent():GetClassInfo():GetClassName() == nbc and win:GetParent():DynamicCast(nbc)
        or nil
        if not notebook then return end
```

Replace `win` with `tree.ctrl` and it should work.

> It does work, in the comments I mention that you set it to 0 and not true, but it's very lazy so I'll change it.

Good point, I haven't noticed that. Maybe then use `tonumber(self:GetConfig().noButtons) or wx.wxTR_HAS_BUTTONS` and the same for `wx.wxTR_LINES_AT_ROOT`, which should take care of non-number values?

**Comment by paul-reilly** [comment]
Thanks, that works! I discovered what was causing it to jump around strangely.... it was using In/SelectItem whilst the notebook (or AuiNotebook) was frozen. I'll leave the calls in with one commented for future travellers. I have one more highlighting issue (highlight isn't changing when clicking on files not already loaded with an editor) to fix and that should be that. He says. :)

**Comment by paul-reilly** [comment]
That's it done I think. The only last minute changes are with comments, so I almost certainly haven't broken it. Sorry about the drama. :)

**Comment by pkulchenko** [comment]
Looks good; thank you! I pulled your changes and did a bit of commit cleanup, but the result should be the same. Pushed the changes to https://github.com/pkulchenko/ZeroBranePackage/tree/tasks; take a quick look and let me know, but should be the exactly the same code as what you have. I'll push it out shortly.

**Comment by paul-reilly** [comment]
You're most welcome, it's been a pleasure getting to play with ZBS's internals... I should be thanking you! Yes, that is indeed exactly the same as I have. But I've just noticed that I missed something in the docs after changing noButtons because there is still...

    noButtons = 0,

... at line 34 in the example config, instead of....

    noButtons = true, 

.... which I assume  would be quicker you changing than involving Git Corp! :)

**Comment by pkulchenko** [comment]
> ...which I assume would be quicker you changing than involving Git Corp! :)

Sure; I'll fix it and merge the changes. Thanks!

**Pull request closed without merging**
