### PR TITLE
MCServer: interpreter breaks into debugger on problem.

### PR DESCRIPTION
**Pull request by madmaxoft**
When MCServer runs into a problem while executing the current Lua code, it will break into ZBS debugger before unloading the plugin.

In order to do so, it has to open the `!EnableMobDebug.lua` file in the editor, so that a breakpoint in that file will make ZBS actually stop. The file is then closed again when debugging terminates.

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Is it possible to make ZeroBrane remove `!EnableMobDebug.lua` once it finished debugging?

**Comment by pkulchenko** [comment]
Not easily, but I can probably add `onDebuggerLoad` and `onDebuggerClose` events and also add a document `Close` event. This will allow you to capture onDebuggerClose event, check that the current interpreter matches the one you are interested in.

**Comment by madmaxoft** [comment]
It already does, most of the time.

**Comment by pkulchenko** [comment]
Unfortunately it's not easy to detect if there is a problem with launching the debugger, as the issue may be with the script or with the debugger itself. This would just leave the same file opened, but it shouldn't be happening frequently, right?

**Comment by madmaxoft** [comment]
No, I've been using this package for months and it has happened about three times.

**Pull request merged**
